CREATE TABLE PRODUCT_PRICES (
   BRAND_ID VARCHAR(36) NOT NULL,
   PRODUCT_ID VARCHAR(36) NOT NULL,
   PRODUCT_RATE VARCHAR(36) NOT NULL,
   START_AT TIMESTAMP NOT NULL,
   END_AT TIMESTAMP NOT NULL,
   PRICE DECIMAL(6,2) NOT NULL,
   PRIORITY INT NOT NULL,
   CURR VARCHAR(36) NOT NULL
);

CREATE INDEX IDX_PRODUCT_PRICES_BRAND_PRODUCT ON PRODUCT_PRICES (BRAND_ID, PRODUCT_ID);